version: '3.0'

services:

    nginx:
        image: nginx:latest
        volumes:
            - './dist/Clubhouse/:/app/'
            - './clubhouse.nginx.conf:/etc/nginx/conf.d/clubhouse.nginx.conf'
        ports:
        -   '8080:8080'
